a = "I am nasreldin altayeb"
b = "I have 24 years old "
print(a)
print(b)
print(a[9])
print(a[5:15])
print(a[::-1])
print(a+" "+b)
print(a.split(" ", 4))
print(a.upper())
print(a.lower())
print(a.isupper())
print(a.islower())
print(a.title())
print(a.capitalize())
print(a *2)
print(a.replace("am", "'m"))
print(a.index("nasr"))
print(a.find("m"))
print(a.count("a"))
print(a.isalpha())
d = "   abc\t123   "
print(d.isalnum())
print(d.isdigit())
print(d.strip())
print(d.lstrip())
print(d.rstrip())
print(d)