a = "ee "
print(a.isspace())
print(100>200)
print(100>100)
print(100>90)
print(100>100.0)
print("#"* 20)
print(bool("eieid"))
print(bool({"e":1}))
print(bool((1,2)))
print(bool([1,2,"mkm"]))
print(bool(True))
print(bool(""))
print(bool({}))
print(bool(()))
print(bool([]))
print(bool(False))
print(bool(0))
# name = input("what\'s your name ")
age =  str (input("how old are you "))
# contary = input("where are you from ")
if name =="nasor" and age > 50 and contary=="sudan":
    print(f"hello {name}\n your age is{age}\n hello people {contary}")
else:
    print("you are not nasor")